security:
    providers:
        simplesaml:
            id: saxid_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/imprint
            anonymous: ~
            context: saml
        saml:
            pattern: ^/
            anonymous: true
            stateless: true
            simple_preauth:
                authenticator: simplesamlphp.authenticator
                provider: simplesaml
            logout:
                path:   /logout
                success_handler: simplesamlphp.logout_handler


    access_control:
        # Make imprint accessible for anonymous access
        - { path: ^/imprint, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,        roles: IS_AUTHENTICATED_FULLY }

    #encoders:
    #    Saxid\SaxidLdapProxyBundle\Security\User\SaxidUser:
    #        algorithm:           sha512
    #        encode_as_base64:    true
    #        iterations:          5000
