saxid_ldap_proxy_tos:
    path:     /
    defaults: { _controller: SaxidLdapProxyBundle:Default:start }

saxid_ldap_proxy_homepage:
    path:     /home
    defaults: { _controller: SaxidLdapProxyBundle:Default:index }

saxid_ldap_proxy_user:
    path:     /user
    defaults:
        _controller: SaxidLdapProxyBundle:Ldap:readuser

saxid_ldap_proxy_imprint:
    path:     /imprint
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    SaxidLdapProxyBundle:Static:imprint.html.twig
        # Cache for one day
        maxAge:      86400
        sharedAge:   86400

saxid_ldap_proxy_password:
    path: /chpwd
    defaults:
        _controller: SaxidLdapProxyBundle:Password:new

saxid_ldap_proxy_testAPI:
    path: /testAPI
    defaults:
        _controller: SaxidLdapProxyBundle:TestAPI:queryapi
