services:
#    saxid_ldap_proxy.example:
#        class:     Saxid\SaxidLdapProxyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    saxid_ldap_proxy.hpc:
        class:      Saxid\SaxidLdapProxyBundle\Services\SaxidServiceHPC


    saxid_ldap_proxy.pwdm:
        class:      Saxid\SaxidLdapProxyBundle\Security\Password\SaxidPasswordManager
        arguments:
